version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /common
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: daily
