FROM node:20-alpine

WORKDIR /npm_cache
COPY frontend/package*.json ./
RUN npm install

WORKDIR /app

ENTRYPOINT [ "/bin/sh", "-c" , "cp -r /npm_cache/node_modules/. /app/node_modules && npm run dev" ]