FROM node:18-alpine  as build-stage

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ .

COPY .env .

COPY common /common

RUN npm run build

FROM nginx as production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html

COPY frontend/nginx.conf /etc/nginx/nginx.conf
