FROM node:20-alpine

LABEL org.opencontainers.image.source=https://github.com/david-loe/abrechnung
LABEL org.opencontainers.image.description="abrechnung🧾 frontend"
LABEL org.opencontainers.image.licenses=AGPL-3.0-only

# install nginx
RUN apk add nginx

COPY frontend/nginx.conf /etc/nginx/nginx.conf

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ .

COPY common /common

ENTRYPOINT [ "/bin/sh", "-c" ]

CMD ["npm run build && nginx -g 'daemon off;'"]
