services:
  backend:
    image: davidloe/abrechnung-backend:2
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - ${BACKEND_PORT}:8000
    env_file:
      - .env

  frontend:
    image: davidloe/abrechnung-frontend:2
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - ${FRONTEND_PORT}:80
    env_file:
      - .env
  
  worker:
    image: davidloe/abrechnung-backend:2
    command: npm run worker
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - .env

  db:
    image: mongo:8
    restart: unless-stopped
    volumes:
      - db_data:/data/db

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
