FROM node:22-alpine

LABEL org.opencontainers.image.source=https://github.com/david-loe/abrechnung
LABEL org.opencontainers.image.description="abrechnung🧾 backend"
LABEL org.opencontainers.image.licenses=AGPL-3.0-only

RUN mkdir /reports

COPY common/package*.json /common/

RUN npm install --prefix /common

COPY common /common

WORKDIR /build

COPY backend/package*.json ./

RUN npm install

COPY backend/ .

RUN npm run build

CMD ["npm", "run", "start"]
