FROM node:18-alpine

RUN mkdir /reports
RUN mkdir /reports/travel
RUN mkdir /reports/expenseReport

WORKDIR /npm_cache
COPY backend/package*.json ./
RUN npm install

WORKDIR /app

ENTRYPOINT [ "/bin/sh", "-c" , "cp -r /npm_cache/node_modules/. /app/node_modules && npm run dev" ]
