FROM node:18-alpine

RUN mkdir /reports
RUN mkdir /reports/travel
RUN mkdir /reports/expenseReport

WORKDIR /build

COPY backend/package*.json ./

RUN npm install

COPY backend/ .

COPY common /common

RUN npm run build

CMD npm run start
