FROM node:24.14-alpine

LABEL org.opencontainers.image.source=https://github.com/david-loe/abrechnung
LABEL org.opencontainers.image.description="abrechnung🧾 common DEVELOPMENT"
LABEL org.opencontainers.image.licenses=AGPL-3.0-only


COPY docker-entrypoint.development.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod 755 /usr/local/bin/docker-entrypoint.sh
ENV DEPENDENCY_SERVICE=common

WORKDIR /npm_cache
COPY package*.json ./
RUN npm ci \
  && sha256sum package.json package-lock.json > .dependency-manifests \
  && cat /proc/sys/kernel/random/uuid > .dependency-id \
  && chown -R node:node /npm_cache \
  && mkdir -p /app && chown node:node /app

WORKDIR /app

USER node
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

CMD ["npm", "run", "dev"]
