name: Build & Test

on:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/production-build.yml

  tests:
    name: Tests
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-development-env
      - name: Start dev Environment
        run: docker compose up -d common db redis ldap inbucket
      - name: Run common tests
        run: docker compose run common npm run test
        # ensures setup runs without error, prevents migration test from failing in next release
      - name: Run backend setup
        run: docker compose run backend npm run setup
      - name: Run backend tests
        run: docker compose run backend npm run test
