name: Setup Production Environment
on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: copy .env file
        uses: canastro/copy-file-action@ae66602ce7d214dbd2e298c1db67a81388755a0a
        with:
          source: '.env.example'
          target: '.env'
      - name: Set production mode in .env
        uses: jacobtomlinson/gha-find-replace@2ff30f644d2e0078fc028beb9193f5ff0dcad39e
        with:
          find: 'NODE_ENV=development'
          replace: 'NODE_ENV=production'
          include: '.env'
      - name: remove dev volume for common
        uses: jacobtomlinson/gha-find-replace@2ff30f644d2e0078fc028beb9193f5ff0dcad39e
        with:
          find: '- ./common:/common:ro'
          replace: ''
          include: 'docker-compose.yml'
          regex: false
